### ISSUE TITLE
Feature Request: Unfold without unfolding sub levels

### ISSUE THREAD

**Issue by sbormann** [denjay/fold-level#1]
Hi, first at all thank you for your great extention!

Would it be possible to add the following feature?

If i have folded to lets say first level 2 and then level 1.
If i now unfold a level 1 region, then everything inside is unfolded, also the level 2 regions.
I would like to unfold level 1 without unfolding the sublevels automatically.
Is that possible?

Many thanks!

**Comment by denjay** [comment]
I added a configuration item: Fold Sub Levels
Check it, Maybe it is what you want.

**Comment by sbormann** [comment]
hi, it's not exactly what I meant, but it's also a very good approach! In any case, it helps me a lot. Thank you very much!
